package pdf

import (
	"fmt"
	"strings"
	"time"

	"github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"github.com/notfixingit3/echostate/internal/models"
)

const (
	maxFieldLen      = 512
	maxRawWHOISLen   = 1024
	maxCopyrights    = 10
	maxErrorsShown   = 20
	pdfDateFormat    = "2006-01-02 15:04:05 UTC"
)

// RenderReport renders a ScanResult as a PDF using maroto v2.
func RenderReport(result *models.ScanResult) ([]byte, error) {
	if result == nil {
		return nil, fmt.Errorf("scan result is nil")
	}

	cfg := config.NewBuilder().
		WithTitle("EchoState Reconnaissance Report", true).
		WithCreator("EchoState", true).
		WithSubject(fmt.Sprintf("Reconnaissance report for %s", result.Host), true).
		WithPageNumber(props.PageNumber{
			Pattern: "Page {current} of {total}",
			Place:   props.Bottom,
			Size:    8,
		}).
		Build()

	m := maroto.New(cfg)

	addCoverPage(m, result)
	addReportMetadata(m, result)
	addSectionHeader(m, "WHOIS")
	addWHOIS(m, result.WHOIS)
	addSectionHeader(m, "ASN / BGP")
	addASN(m, result.ASN)
	addSectionHeader(m, "Web / Copyright")
	addWeb(m, result.Web)

	if len(result.Errors) > 0 {
		addSectionHeader(m, "Errors")
		addErrors(m, result.Errors)
	}

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate PDF: %w", err)
	}

	return doc.GetBytes(), nil
}

func addCoverPage(m core.Maroto, result *models.ScanResult) {
	m.AddRows(row.New(40).Add(col.New(12)))

	m.AddRows(
		text.NewRow(14, "EchoState Reconnaissance Report", props.Text{
			Size:  22,
			Style: fontstyle.Bold,
			Align: align.Center,
		}),
	)

	m.AddRows(row.New(10).Add(col.New(12)))

	scannedAt := result.ScannedAt.Format(pdfDateFormat)
	if result.ScannedAt.IsZero() {
		scannedAt = "N/A"
	}

	m.AddRows(
		text.NewRow(8, fmt.Sprintf("Target: %s", valueOrNA(result.Host)), props.Text{
			Size:  12,
			Align: align.Center,
		}),
		text.NewRow(8, fmt.Sprintf("Scanned At: %s", scannedAt), props.Text{
			Size:  12,
			Align: align.Center,
		}),
	)

	m.AddRows(row.New(20).Add(col.New(12)))

	m.AddRows(
		text.NewRow(6, "Generated by EchoState", props.Text{
			Size:  8,
			Align: align.Center,
			Style: fontstyle.Italic,
		}),
	)
}

func addReportMetadata(m core.Maroto, result *models.ScanResult) {
	addSectionHeader(m, "Report Metadata")

	addKeyValueRow(m, "Report Generated At", time.Now().UTC().Format(pdfDateFormat))
	addKeyValueRow(m, "Target", valueOrNA(result.Host))

	scannedAt := result.ScannedAt.Format(pdfDateFormat)
	if result.ScannedAt.IsZero() {
		scannedAt = "N/A"
	}
	addKeyValueRow(m, "Scanned At", scannedAt)
}

func addSectionHeader(m core.Maroto, title string) {
	m.AddRows(row.New(4).Add(col.New(12)))
	m.AddRows(
		text.NewRow(10, title, props.Text{
			Size:  14,
			Style: fontstyle.Bold,
		}),
	)
}

func addWHOIS(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No WHOIS data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "Domain", stringVal(data, "domain"))
	addKeyValueRow(m, "Registrar", stringVal(data, "registrar"))
	addKeyValueRow(m, "Expiration Date", stringVal(data, "expiration_date"))
	addKeyValueRow(m, "Name Servers", stringVal(data, "name_servers"))
	addKeyValueRow(m, "Status", stringVal(data, "status"))

	if raw, ok := data["raw"].(string); ok && raw != "" {
		addKeyValueRow(m, "Raw Record", truncate(raw, maxRawWHOISLen))
	}
}

func addASN(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No ASN/BGP data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "ASN", stringVal(data, "asn"))
	addKeyValueRow(m, "Prefix", stringVal(data, "prefix"))
	addKeyValueRow(m, "Country", stringVal(data, "country"))
	addKeyValueRow(m, "Registry", stringVal(data, "registry"))
	addKeyValueRow(m, "Allocated", stringVal(data, "allocated"))
	addKeyValueRow(m, "AS Name", stringVal(data, "as_name"))
	addKeyValueRow(m, "IP", stringVal(data, "ip"))
}

func addWeb(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No web data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "Title", stringVal(data, "title"))
	addKeyValueRow(m, "URL", stringVal(data, "url"))

	copyrights := extractCopyrights(data)
	if len(copyrights) == 0 {
		addKeyValueRow(m, "Copyrights", "None detected")
		return
	}

	m.AddRows(
		text.NewRow(6, "Copyrights:", props.Text{Size: 10, Style: fontstyle.Bold}),
	)
	for _, c := range copyrights {
		m.AddRows(
			text.NewRow(5, "• "+truncate(c, maxFieldLen), props.Text{Size: 9}),
		)
	}
}

func addErrors(m core.Maroto, errors []string) {
	for i, err := range errors {
		if i >= maxErrorsShown {
			m.AddRows(text.NewRow(6, fmt.Sprintf("... and %d more error(s)", len(errors)-maxErrorsShown), props.Text{Size: 9, Style: fontstyle.Italic}))
			break
		}
		m.AddRows(
			text.NewRow(5, "• "+truncate(err, maxFieldLen), props.Text{Size: 9}),
		)
	}
}

func addKeyValueRow(m core.Maroto, label, value string) {
	m.AddRows(
		row.New(6).Add(
			text.NewCol(3, label+":", props.Text{Size: 10, Style: fontstyle.Bold}),
			text.NewCol(9, value, props.Text{Size: 10}),
		),
	)
}

func stringVal(data map[string]any, key string) string {
	if data == nil {
		return "N/A"
	}

	v, ok := data[key]
	if !ok || v == nil {
		return "N/A"
	}

	switch s := v.(type) {
	case string:
		if strings.TrimSpace(s) == "" {
			return "N/A"
		}
		return truncate(s, maxFieldLen)
	case []string:
		if len(s) == 0 {
			return "N/A"
		}
		return truncate(strings.Join(s, ", "), maxFieldLen)
	case []any:
		if len(s) == 0 {
			return "N/A"
		}
		var parts []string
		for _, item := range s {
			if item == nil {
				continue
			}
			parts = append(parts, fmt.Sprintf("%v", item))
		}
		if len(parts) == 0 {
			return "N/A"
		}
		return truncate(strings.Join(parts, ", "), maxFieldLen)
	case time.Time:
		return s.Format(pdfDateFormat)
	default:
		str := fmt.Sprintf("%v", v)
		if strings.TrimSpace(str) == "" {
			return "N/A"
		}
		return truncate(str, maxFieldLen)
	}
}

func extractCopyrights(data map[string]any) []string {
	if data == nil {
		return nil
	}

	v, ok := data["copyrights"]
	if !ok || v == nil {
		return nil
	}

	var out []string
	seen := make(map[string]struct{})

	add := func(s string) {
		s = strings.TrimSpace(s)
		if s == "" {
			return
		}
		if _, exists := seen[s]; exists {
			return
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}

	switch s := v.(type) {
	case []string:
		for _, item := range s {
			add(item)
		}
	case []any:
		for _, item := range s {
			if item == nil {
				continue
			}
			if str, ok := item.(string); ok {
				add(str)
			}
		}
	case string:
		add(s)
	}

	if len(out) > maxCopyrights {
		out = out[:maxCopyrights]
	}

	return out
}

func valueOrNA(s string) string {
	if strings.TrimSpace(s) == "" {
		return "N/A"
	}
	return s
}

func truncate(s string, n int) string {
	if n <= 0 {
		return s
	}
	if len(s) <= n {
		return s
	}
	if n <= 3 {
		return s[:n]
	}
	return s[:n-3] + "..."
}
