package pdf

import (
	"fmt"
	"strings"
	"time"

	"github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/image"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/extension"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/props"

	"github.com/notfixingit3/echostate/internal/models"
)

const (
	maxFieldLen        = 512
	maxRawWHOISLen     = 1024
	maxCopyrights      = 10
	maxErrorsShown     = 20
	maxChangesShown    = 25
	maxChangeDetails   = 20
	pdfDateFormat      = "2006-01-02 15:04:05 UTC"
	coverLogoHeight    = 28.0
	screenshotRowHeight = 55.0
)

// RenderReport renders snapshot reconnaissance data as a PDF using maroto v2.
func RenderReport(data ReportData) ([]byte, error) {
	if data.Result == nil {
		return nil, fmt.Errorf("scan result is nil")
	}
	result := data.Result

	cfg := config.NewBuilder().
		WithTitle("EchoState Reconnaissance Report", true).
		WithCreator("EchoState", true).
		WithSubject(fmt.Sprintf("Reconnaissance report for %s", result.Host), true).
		WithPageNumber(props.PageNumber{
			Pattern: "Page {current} of {total}",
			Place:   props.Bottom,
			Size:    8,
		}).
		Build()

	m := maroto.New(cfg)

	addCoverPage(m, result)
	addReportMetadata(m, result)
	addIntelHighlights(m, result)
	addChanges(m, data.Changes, data.ChangeDetails)
	addScreenshot(m, data.ScreenshotJPEG, result.Screenshot)
	addSectionHeader(m, "WHOIS")
	addWHOIS(m, result.WHOIS)
	addSectionHeader(m, "ASN / BGP")
	addASN(m, result.ASN)
	addSectionHeader(m, "DNS")
	addDNS(m, result.DNS)
	addSectionHeader(m, "TLS / Certificate")
	addTLS(m, result.TLS)
	addSectionHeader(m, "Web / Copyright")
	addWeb(m, result.Web)

	if len(result.Errors) > 0 {
		addSectionHeader(m, "Errors")
		addErrors(m, result.Errors)
	}

	doc, err := m.Generate()
	if err != nil {
		return nil, fmt.Errorf("generate PDF: %w", err)
	}

	return doc.GetBytes(), nil
}

func addCoverPage(m core.Maroto, result *models.ScanResult) {
	m.AddRows(row.New(12).Add(col.New(12)))

	if len(logoPNG) > 0 {
		m.AddRows(
			image.NewFromBytesRow(coverLogoHeight, logoPNG, extension.Png, props.Rect{
				Center:  true,
				Percent: 45,
			}),
		)
		m.AddRows(row.New(6).Add(col.New(12)))
	}

	m.AddRows(
		text.NewRow(14, "EchoState Reconnaissance Report", props.Text{
			Size:  22,
			Style: fontstyle.Bold,
			Align: align.Center,
		}),
	)

	m.AddRows(row.New(8).Add(col.New(12)))

	scannedAt := result.ScannedAt.Format(pdfDateFormat)
	if result.ScannedAt.IsZero() {
		scannedAt = "N/A"
	}

	m.AddRows(
		text.NewRow(8, fmt.Sprintf("Target: %s", valueOrNA(result.Host)), props.Text{
			Size:  12,
			Align: align.Center,
		}),
		text.NewRow(8, fmt.Sprintf("Scanned At: %s", scannedAt), props.Text{
			Size:  12,
			Align: align.Center,
		}),
	)

	m.AddRows(row.New(16).Add(col.New(12)))

	m.AddRows(
		text.NewRow(6, "Passive reconnaissance intelligence report", props.Text{
			Size:  9,
			Align: align.Center,
			Style: fontstyle.Italic,
		}),
		text.NewRow(6, "Generated by EchoState · echostate.io", props.Text{
			Size:  8,
			Align: align.Center,
			Style: fontstyle.Italic,
		}),
	)
}

func addReportMetadata(m core.Maroto, result *models.ScanResult) {
	addSectionHeader(m, "Report Metadata")

	addKeyValueRow(m, "Report Generated At", time.Now().UTC().Format(pdfDateFormat))
	addKeyValueRow(m, "Target", valueOrNA(result.Host))

	scannedAt := result.ScannedAt.Format(pdfDateFormat)
	if result.ScannedAt.IsZero() {
		scannedAt = "N/A"
	}
	addKeyValueRow(m, "Scanned At", scannedAt)
}

func addIntelHighlights(m core.Maroto, result *models.ScanResult) {
	addSectionHeader(m, "Intel Highlights")

	addKeyValueRow(m, "JARM", stringVal(result.TLS, "jarm"))
	addKeyValueRow(m, "JA3S", stringVal(result.TLS, "ja3s"))
	addKeyValueRow(m, "Favicon MMH3", stringVal(result.Favicon, "mmh3"))
	addKeyValueRow(m, "Cert Expires", stringVal(result.TLS, "not_after"))
	addKeyValueRow(m, "Cert Issuer", stringVal(result.TLS, "issuer"))
	addKeyValueRow(m, "DNS A/AAAA", joinDNSRecords(result.DNS))
	addKeyValueRow(m, "CT Subdomains", stringVal(result.CT, "count"))
}

func addChanges(m core.Maroto, changes []string, details []models.ChangeDetail) {
	if len(changes) == 0 && len(details) == 0 {
		return
	}

	addSectionHeader(m, "Snapshot Changes")

	if len(details) > 0 {
		m.AddRows(
			text.NewRow(6, "Structured changes:", props.Text{Size: 10, Style: fontstyle.Bold}),
		)
		for i, detail := range details {
			if i >= maxChangeDetails {
				m.AddRows(text.NewRow(6, fmt.Sprintf("... and %d more change(s)", len(details)-maxChangeDetails), props.Text{Size: 9, Style: fontstyle.Italic}))
				break
			}
			line := fmt.Sprintf("[%s/%s] %s", strings.ToUpper(detail.Severity), detail.Type, detail.Summary)
			if detail.Field != "" {
				line = fmt.Sprintf("%s (%s)", line, detail.Field)
			}
			m.AddRows(
				text.NewRow(5, "• "+truncate(line, maxFieldLen), props.Text{Size: 9}),
			)
		}
	}

	if len(changes) > 0 {
		m.AddRows(
			text.NewRow(6, "Summary:", props.Text{Size: 10, Style: fontstyle.Bold}),
		)
		for i, change := range changes {
			if i >= maxChangesShown {
				m.AddRows(text.NewRow(6, fmt.Sprintf("... and %d more change(s)", len(changes)-maxChangesShown), props.Text{Size: 9, Style: fontstyle.Italic}))
				break
			}
			m.AddRows(
				text.NewRow(5, "• "+truncate(change, maxFieldLen), props.Text{Size: 9}),
			)
		}
	}
}

func addScreenshot(m core.Maroto, jpeg []byte, meta map[string]any) {
	if len(jpeg) == 0 && len(meta) == 0 {
		return
	}

	addSectionHeader(m, "Web Screenshot")

	if len(jpeg) > 0 {
		m.AddRows(
			image.NewFromBytesRow(screenshotRowHeight, jpeg, extension.Jpeg, props.Rect{
				Center:  true,
				Percent: 80,
			}),
		)
	}

	if len(meta) > 0 {
		addKeyValueRow(m, "URL", stringVal(meta, "url"))
		addKeyValueRow(m, "Dimensions", screenshotDimensions(meta))
		if errMsg := stringVal(meta, "error"); errMsg != "N/A" {
			addKeyValueRow(m, "Capture Error", errMsg)
		}
	} else if len(jpeg) == 0 {
		m.AddRows(text.NewRow(6, "No screenshot available.", props.Text{Size: 10}))
	}
}

func addSectionHeader(m core.Maroto, title string) {
	m.AddRows(row.New(4).Add(col.New(12)))
	m.AddRows(
		text.NewRow(10, title, props.Text{
			Size:  14,
			Style: fontstyle.Bold,
		}),
	)
}

func addWHOIS(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No WHOIS data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "Domain", stringVal(data, "domain"))
	addKeyValueRow(m, "Registrar", stringVal(data, "registrar"))
	addKeyValueRow(m, "Expiration Date", stringVal(data, "expiration_date"))
	addKeyValueRow(m, "Name Servers", stringVal(data, "name_servers"))
	addKeyValueRow(m, "Status", stringVal(data, "status"))

	if raw, ok := data["raw"].(string); ok && raw != "" {
		addKeyValueRow(m, "Raw Record", truncate(raw, maxRawWHOISLen))
	}
}

func addASN(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No ASN/BGP data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "ASN", stringVal(data, "asn"))
	addKeyValueRow(m, "Prefix", stringVal(data, "prefix"))
	addKeyValueRow(m, "Country", stringVal(data, "country"))
	addKeyValueRow(m, "Registry", stringVal(data, "registry"))
	addKeyValueRow(m, "Allocated", stringVal(data, "allocated"))
	addKeyValueRow(m, "AS Name", stringVal(data, "as_name"))
	addKeyValueRow(m, "IP", stringVal(data, "ip"))
}

func addDNS(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No DNS data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "A / AAAA", joinDNSRecords(data))
	addKeyValueRow(m, "MX", stringVal(data, "mx"))
	addKeyValueRow(m, "NS", stringVal(data, "ns"))
	addKeyValueRow(m, "TXT", stringVal(data, "txt"))
	addKeyValueRow(m, "CNAME", stringVal(data, "cname"))
	addKeyValueRow(m, "DMARC", stringVal(data, "dmarc"))
	addKeyValueRow(m, "SPF", stringVal(data, "spf"))
}

func addTLS(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No TLS data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "Subject", stringVal(data, "subject"))
	addKeyValueRow(m, "Issuer", stringVal(data, "issuer"))
	addKeyValueRow(m, "Not Before", stringVal(data, "not_before"))
	addKeyValueRow(m, "Not After", stringVal(data, "not_after"))
	addKeyValueRow(m, "Days Remaining", stringVal(data, "days_remaining"))
	addKeyValueRow(m, "JARM", stringVal(data, "jarm"))
	addKeyValueRow(m, "JA3S", stringVal(data, "ja3s"))
}

func addWeb(m core.Maroto, data map[string]any) {
	if len(data) == 0 {
		m.AddRows(text.NewRow(6, "No web data available.", props.Text{Size: 10}))
		return
	}

	addKeyValueRow(m, "Title", stringVal(data, "title"))
	addKeyValueRow(m, "URL", stringVal(data, "url"))

	copyrights := extractCopyrights(data)
	if len(copyrights) == 0 {
		addKeyValueRow(m, "Copyrights", "None detected")
		return
	}

	m.AddRows(
		text.NewRow(6, "Copyrights:", props.Text{Size: 10, Style: fontstyle.Bold}),
	)
	for _, c := range copyrights {
		m.AddRows(
			text.NewRow(5, "• "+truncate(c, maxFieldLen), props.Text{Size: 9}),
		)
	}
}

func addErrors(m core.Maroto, errors []string) {
	for i, err := range errors {
		if i >= maxErrorsShown {
			m.AddRows(text.NewRow(6, fmt.Sprintf("... and %d more error(s)", len(errors)-maxErrorsShown), props.Text{Size: 9, Style: fontstyle.Italic}))
			break
		}
		m.AddRows(
			text.NewRow(5, "• "+truncate(err, maxFieldLen), props.Text{Size: 9}),
		)
	}
}

func addKeyValueRow(m core.Maroto, label, value string) {
	m.AddRows(
		row.New(6).Add(
			text.NewCol(3, label+":", props.Text{Size: 10, Style: fontstyle.Bold}),
			text.NewCol(9, value, props.Text{Size: 10}),
		),
	)
}

func joinDNSRecords(data map[string]any) string {
	if len(data) == 0 {
		return "N/A"
	}
	a := stringVal(data, "a")
	aaaa := stringVal(data, "aaaa")
	if a == "N/A" && aaaa == "N/A" {
		return "N/A"
	}
	if a == "N/A" {
		return aaaa
	}
	if aaaa == "N/A" {
		return a
	}
	return a + "; " + aaaa
}

func screenshotDimensions(meta map[string]any) string {
	width := stringVal(meta, "width")
	height := stringVal(meta, "height")
	if width == "N/A" || height == "N/A" {
		return "N/A"
	}
	return width + " × " + height
}

func stringVal(data map[string]any, key string) string {
	if data == nil {
		return "N/A"
	}

	v, ok := data[key]
	if !ok || v == nil {
		return "N/A"
	}

	switch s := v.(type) {
	case string:
		if strings.TrimSpace(s) == "" {
			return "N/A"
		}
		return truncate(s, maxFieldLen)
	case []string:
		if len(s) == 0 {
			return "N/A"
		}
		return truncate(strings.Join(s, ", "), maxFieldLen)
	case []any:
		if len(s) == 0 {
			return "N/A"
		}
		var parts []string
		for _, item := range s {
			if item == nil {
				continue
			}
			parts = append(parts, fmt.Sprintf("%v", item))
		}
		if len(parts) == 0 {
			return "N/A"
		}
		return truncate(strings.Join(parts, ", "), maxFieldLen)
	case time.Time:
		return s.Format(pdfDateFormat)
	default:
		str := fmt.Sprintf("%v", v)
		if strings.TrimSpace(str) == "" {
			return "N/A"
		}
		return truncate(str, maxFieldLen)
	}
}

func extractCopyrights(data map[string]any) []string {
	if data == nil {
		return nil
	}

	v, ok := data["copyrights"]
	if !ok || v == nil {
		return nil
	}

	var out []string
	seen := make(map[string]struct{})

	add := func(s string) {
		s = strings.TrimSpace(s)
		if s == "" {
			return
		}
		if _, exists := seen[s]; exists {
			return
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}

	switch s := v.(type) {
	case []string:
		for _, item := range s {
			add(item)
		}
	case []any:
		for _, item := range s {
			if item == nil {
				continue
			}
			if str, ok := item.(string); ok {
				add(str)
			}
		}
	case string:
		add(s)
	}

	if len(out) > maxCopyrights {
		out = out[:maxCopyrights]
	}

	return out
}

func valueOrNA(s string) string {
	if strings.TrimSpace(s) == "" {
		return "N/A"
	}
	return s
}

func truncate(s string, n int) string {
	if n <= 0 {
		return s
	}
	if len(s) <= n {
		return s
	}
	if n <= 3 {
		return s[:n]
	}
	return s[:n-3] + "..."
}